<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice</title>
    <style>
        /* General Styling */
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
            text-transform: uppercase;
            background-color: #f8f8f8;
        }

        .container {
            width: 100%;
            max-width: 900px;
            margin: 30px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        /* Header Styling */
        .header {
            width: 100%;
            margin-bottom: 20px;
            text-align: left;
            border-bottom: 4px solid #ff6c00;
            padding-bottom: 10px;
        }

        .header table {
            width: 100%;
            border-collapse: collapse;
        }

        .header td {
            vertical-align: top;
        }

        .company-name {
            font-size: 22px;
            font-weight: bold;
            color: #ff6c00;
        }

        .company-info {
            font-size: 14px;
            color: #555;
        }

        .logo {
            max-width: 120px;
        }

        /* Invoice Title */
        .invoice-title {
            text-align: center;
            font-size: 28px;
            color: #ff6c00;
            font-weight: bold;
            margin: 20px 0;
        }

        /* Invoice Details */
        .invoice-details {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .invoice-details td {
            padding: 8px;
            font-size: 14px;
            vertical-align: top;
        }

        .invoice-details td strong {
            color: #333;
            font-size: 16px;
        }

        /* Table Styling */
        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
        }

        th, td {
            padding: 10px;
            border: 1px solid #ddd;
            text-align: center;
            font-size: 14px;
        }

        thead {
            background-color: #ff6c00;
            color: white;
            font-size: 16px;
        }

        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        /* Footer Note */
        .footer-note {
            text-align: center;
            font-size: 12px;
            color: #777;
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
        }
    </style>
</head>

<body>
<div class="container">
    <!-- Header Section -->
    <table class="header">
        <tr>
            <td width="60%">
                <span class="company-name">K2D</span>
                <p class="company-info">MIRPUR, DHAKA<br>BANGLADESH</p>
            </td>
            <td width="40%" align="right">
                <img src="{{ asset('assets/img/logo1.png') }}" alt="Logo" class="logo">
            </td>
        </tr>
    </table>

    <!-- Invoice Title -->
    <div class="invoice-title">
        <p>Invoice</p>
    </div>

    <!-- Invoice Details -->
    <table class="invoice-details">
        <tr>
            <td width="50%">
                <strong>Invoice To:</strong><br>
                <p>{{ $transaction->recipient }}</p>
            </td>
            <td width="50%" align="right">
                <strong>Invoice ID:</strong> {{ $transaction->id }}<br>
                <strong>Date:</strong> {{ \Carbon\Carbon::parse($transaction->date)->format('d M, Y') }}
            </td>
        </tr>
    </table>

    <!-- Payment Table Section -->
    <table>
        <thead>
        <tr>
            <th>Sl</th>
            <th>Bank</th>
            <th>Amount</th>

            <th>Payment Mode</th>
            <th>Category</th>
            <th>Notes</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>{{ $transaction->bank->name ?? 'N/A' }}</td>
            <td>{{ number_format($transaction->amount, 2) }}</td>

            <td>{{ ucfirst($transaction->payment_mode) }}</td>
            <td>{{ ucfirst(str_replace('_', ' ', $transaction->category)) }}</td>
            <td>{{ $transaction->notes ?? 'N/A' }}</td>
            <td>{{ \Carbon\Carbon::parse($transaction->date)->format('d M, Y') }}</td>
        </tr>
        </tbody>
    </table>

    <!-- Footer Note -->
    <div class="footer-note">
        <p>This invoice was generated by Kolkata 2 Dhaka. For any queries, please contact us.</p>
    </div>
</div>
</body>

</html>
